# Generated by Django 4.2.10 on 2024-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manilsnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
