# Generated by Django 4.2.10 on 2024-02-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manilsnews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Stories',
        ),
    ]
